// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmb69qbDlG4i0soWoyJyqJ2D4b2opwTo8',
    appId: '1:369174040690:web:16e3377604f31e59bfb2eb',
    messagingSenderId: '369174040690',
    projectId: 'balance-ai-agent-49377',
    authDomain: 'balance-ai-agent-49377.firebaseapp.com',
    storageBucket: 'balance-ai-agent-49377.firebasestorage.app',
    measurementId: 'G-29BMLSE6R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZGvQB6ro4ZdAxZGuxenHzBncS9SJax-I',
    appId: '1:369174040690:android:7641b0546d2f7b6fbfb2eb',
    messagingSenderId: '369174040690',
    projectId: 'balance-ai-agent-49377',
    storageBucket: 'balance-ai-agent-49377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeo6kns_Xi7fR3MWXTHSghjzN7c112n-k',
    appId: '1:369174040690:ios:39e34a94c46ed373bfb2eb',
    messagingSenderId: '369174040690',
    projectId: 'balance-ai-agent-49377',
    storageBucket: 'balance-ai-agent-49377.firebasestorage.app',
    iosBundleId: 'com.example.balanceAiAgent',
  );
}
