name: Deploy to Firebase Functions

on:
  workflow_run:
    workflows: ["backend_ci"]
    types: 
      - completed
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './functions/package-lock.json'
    
    - name: Debug token availability
      run: |
        echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN exists: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN != '' }}"
        echo "ACTIONS_ID_TOKEN_REQUEST_URL exists: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL != '' }}"

    - name: Install dependencies
      working-directory: ./functions
      run: npm ci
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Decode service-account-key.json from secret
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}" | base64 -d > "./functions/service-account-key.json"
    
      # 認証
    - name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v2"
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        create_credentials_file: true
        export_environment_variables: true

    # Cloud Functions for Firebase にデプロイ
    - name: Deploy to Functions
      run: |
        npm install -g firebase-tools
        firebase deploy --only functions --force --project=bar-project