name: flutter ci
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create firebase_options.dart
        run: |
          echo "$FIREBASE_OPTIONS_BASE64" | base64 -d > lib/firebase_options.dart
        env:
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install packages
        run: flutter pub get && flutter pub get
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test